services:
  - type: web
    name: avtoibrat
    runtime: python
    plan: free
    rootDir: core
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /uz/login/
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEMO_PASSWORD
        generateValue: true
