# Generated by Django 4.2 on 2026-01-04 02:25

import avto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="audio",
        ),
        migrations.AddField(
            model_name="question",
            name="audio_rus",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="questions/audio/",
                validators=[avto.models.validate_audio_duration],
                verbose_name="Audio (Русский)",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="audio_uzb",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="questions/audio/",
                validators=[avto.models.validate_audio_duration],
                verbose_name="Audio (O‘zbek lotin/krill)",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="matn",
            field=models.TextField(verbose_name="Savol matni"),
        ),
        migrations.AlterField(
            model_name="question",
            name="rasm",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="questions/images/",
                validators=[avto.models.validate_question_image],
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="video_url",
            field=models.URLField(blank=True, null=True, verbose_name="Video URL"),
        ),
    ]
