# Generated by Django 4.2 on 2026-01-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avto", "0002_remove_question_audio_question_audio_rus_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="matn",
        ),
        migrations.AddField(
            model_name="question",
            name="matn_ru",
            field=models.TextField(default=4, verbose_name="Savol matni (Русский)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="matn_uz",
            field=models.TextField(
                default=2, verbose_name="Savol matni (O‘zbek lotin)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="matn_uz_kr",
            field=models.TextField(default=2, verbose_name="Savol matni (Ўзбек крилл)"),
            preserve_default=False,
        ),
    ]
