# Generated by Django 4.2 on 2026-01-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avto", "0003_remove_question_matn_question_matn_ru_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="matn_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="matn_uz",
        ),
        migrations.RemoveField(
            model_name="question",
            name="matn_uz_kr",
        ),
        migrations.AddField(
            model_name="question",
            name="matn",
            field=models.TextField(default=2, verbose_name="Savol matni"),
            preserve_default=False,
        ),
    ]
