# Generated by Django 4.2 on 2026-01-04 12:48

import avto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avto", "0004_remove_question_matn_ru_remove_question_matn_uz_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="matn",
            new_name="matn_rus",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="savol",
            new_name="question",
        ),
        migrations.AddField(
            model_name="answer",
            name="matn_uzb",
            field=models.CharField(default=22, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="matn_rus",
            field=models.TextField(default=4, verbose_name="Savol (Русский)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="matn_uzb",
            field=models.TextField(
                default=2, verbose_name="Savol (O‘zbek lotin/krill)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="audio_rus",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="questions/audio/",
                validators=[avto.models.validate_audio_duration],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="audio_uzb",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="questions/audio/",
                validators=[avto.models.validate_audio_duration],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="matn",
            field=models.TextField(blank=True, verbose_name="Savol (legacy)"),
        ),
        migrations.AlterField(
            model_name="question",
            name="rasm",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="questions/images/",
                validators=[avto.models.validate_question_image],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
