# Generated by Django 4.2 on 2026-01-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("avto", "0005_rename_matn_answer_matn_rus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="matn_uz_kr",
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="matn_uz_kr",
            field=models.TextField(default=2, verbose_name="Savol (Крил)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="matn_uzb",
            field=models.TextField(verbose_name="Savol (O‘zbek)"),
        ),
    ]
