# Generated by Django 6.0 on 2026-09-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0006_answer_matn_uz_kr_question_matn_uz_kr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
