# Generated by Django 6.0 on 2026-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0007_testsession_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_language',
            field=models.CharField(choices=[('uz', 'Oʻzbek guruhi (lotin)'), ('uz-kr', 'Ўзбек гуруҳи (кирилл)'), ('ru', 'Русская группа')], default='uz', help_text='Talaba savol va javoblarni shu tilda ko‘radi. Sayt interfeysi tilidan mustaqil.', max_length=10, verbose_name='Guruh tili'),
        ),
    ]
