# Generated by Django 6.0 on 2026-09-20 12:31

import django.core.validators
import django.db.models.deletion
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0008_user_group_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=150, verbose_name='Avtomaktab')),
                ('name', models.CharField(max_length=150, verbose_name='Filial')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'ordering': ['school_name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, help_text='Masalan: AD 1234567', max_length=10, validators=[django.core.validators.RegexValidator(message='Pasport raqami «AD 1234567» ko‘rinishida bo‘lishi kerak.', regex=re.compile('^[A-Z]{2} ?\\d{7}$', 2))], verbose_name='Pasport raqami'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_end',
            field=models.DateField(blank=True, null=True, verbose_name='Ta’lim tugaydigan sana'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_start',
            field=models.DateField(blank=True, null=True, verbose_name='Ta’lim boshlangan sana'),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Guruh raqami yoki nomi')),
                ('category', models.CharField(choices=[('A', 'A — mototsikl'), ('B', 'B — yengil avtomobil'), ('BC', 'BC — yengil va yuk avtomobili'), ('C', 'C — yuk avtomobili'), ('D', 'D — avtobus')], max_length=2, verbose_name='Ta’lim toifasi')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='avto.branch', verbose_name='Filial')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_groups', to=settings.AUTH_USER_MODEL, verbose_name='O‘qituvchi')),
            ],
            options={
                'verbose_name': 'O‘quv guruhi',
                'verbose_name_plural': 'O‘quv guruhlari',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='avto.studygroup', verbose_name='O‘quv guruhi'),
        ),
    ]
