# Generated by Django 6.0 on 2026-09-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0009_branch_user_birth_date_user_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsession',
            name='source',
            field=models.CharField(choices=[('shablon', 'Shablon'), ('mavzu', 'Mavzulashtirilgan'), ('ohshash', 'O‘xshash'), ('saqlangan', 'Saqlangan savollar')], default='shablon', max_length=20),
        ),
    ]
