# Generated by Django 6.0 on 2026-09-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0010_saqlangan_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadsign',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='roadsigncategory',
            options={'ordering': ['order', 'id'], 'verbose_name_plural': 'road sign categories'},
        ),
        migrations.AddField(
            model_name='roadsign',
            name='number',
            field=models.CharField(blank=True, help_text='e.g. 1.1 or 1.4.2', max_length=20),
        ),
        migrations.AddField(
            model_name='roadsign',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadsigncategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roadsign',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
