# Generated by Django 6.0 on 2026-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0011_road_sign_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='initial_password',
            field=models.CharField(blank=True, help_text='Faqat xodimlarga ko‘rinadi — talaba parolni unutsa, o‘qituvchi shu yerdan aytadi.', max_length=64, verbose_name='Talaba paroli'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='O‘qituvchi tomonidan o‘chirilgan hisob: muddatidan qat’i nazar kira olmaydi.', verbose_name='Bloklangan'),
        ),
    ]
