# Generated by Django 6.0 on 2026-10-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0012_student_block_and_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='lesson_time',
            field=models.CharField(blank=True, help_text='Masalan: Du-Chor-Ju, 18:00–20:00', max_length=100, verbose_name='Dars vaqti'),
        ),
    ]
