# Generated by Django 6.0 on 2026-10-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0014_open_ended_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='lesson_time',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='lesson_days',
            field=models.CharField(blank=True, help_text='1 = dushanba … 7 = yakshanba, masalan «135».', max_length=7, verbose_name='Dars kunlari'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='lesson_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Dars tugashi'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='lesson_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Dars boshlanishi'),
        ),
    ]
