# Generated by Django 6.0 on 2026-10-09 11:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0016_monitoring_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_express',
            field=models.BooleanField(default=False, help_text='Express kursi talabalari o‘qituvchi bergan kunlik test vazifasini bajaradi.', verbose_name='Express kursida'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Vazifa nomi')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('audience', models.CharField(choices=[('express', 'Express kursi talabalari'), ('group', 'Bitta guruh')], default='express', max_length=10, verbose_name='Kimlar uchun')),
                ('tests_per_day', models.PositiveSmallIntegerField(default=25, help_text='Bitta test — bitta tugatilgan test (masalan, 20 savoldan iborat).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)], verbose_name='Kuniga testlar soni')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, help_text='Bo‘sh qoldirilsa — muddatsiz.', null=True, verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='avto.studygroup', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-is_active', '-start_date', '-created_at'],
            },
        ),
    ]
