# Generated by Django 6.0 on 2026-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0017_express_and_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Bo‘sh bo‘lsa — toifadagi standart vaqt (marafonda savollar soniga qarab belgilanadi).', null=True, verbose_name='Vaqt (daqiqa)'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='source',
            field=models.CharField(choices=[('shablon', 'Shablon'), ('mavzu', 'Mavzulashtirilgan'), ('ohshash', 'O‘xshash'), ('saqlangan', 'Saqlangan savollar'), ('marafon', 'Marafon')], default='shablon', max_length=20),
        ),
    ]
