# Generated by Django 6.0 on 2026-10-09 12:42

import avto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0018_marathon_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='video_url',
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='questions/video/', validators=[avto.models.validate_video_file], verbose_name='Video'),
        ),
    ]
